### PR TITLE
Overhaul of DRU and LBR

### PR DESCRIPTION
**Pull request by onibrow**
Add description and links for BBB and Arduino Pro Micro

Add a better description for the DRU and how it was adopted for PiE's
use, modelled for Advanced Circuits

Add wago screw terminals 2,3,4 pin
TODO: Make sure the dimensions are correct, possibly even create new
parts to fit the current screw terminals in stock

### CODE REVIEW

**Comment by tobinsarah** [comment]
I'm getting a "parse error in line 1" when I try to open the .dru file. Which is weird because you didn't change it according to git... But it definitely looks like it's missing the </p> tag and spaces after some of the new line characters. That could be the problem.

For the WAGO terminals, can you make the symbol more representative? Or at least add a >NAME label for the part as a whole so it's not just a group of pins?

**Comment by onibrow** [comment]
I'm not sure why you're getting `parse error` because I can open it just fine.

I'll go ahead and add more to the symbols.

**Comment by tobinsarah** [comment]
UPDATE: pie.dru is fine. I was confusing it with a different dru file (actually the one I downloaded during worksession on Saturday so we may need to look into that later).

Why did you close the pull request? Is there some pull request ettiquette/procedure that I'm not aware of? :P

**Comment by onibrow** [comment]
I'm gonna make a new clean one! Is there way to update the commit without closing and reopening?

**Comment by tobinsarah** [comment]
- the drill of the pin holes is too small: currently 1.19mm, should be at least 1.3 mm (I would make them 1.35mm to be safer).

This is based on the dimensions match the sparkfun drawing (https://www.sparkfun.com/datasheets/Prototyping/Screw-Terminal-5mm.pdf) pretty closely. 


I'm not sure 4-pin screw terminals exist in the compact form factor like the WAGO-237 series you mention -- although Sparkfun's version slide locks together so we can make our own.

Also I would like to have links to drawing/ordering stuff in the device descriptions at least; I'm happy to add that at a later date though (or if its easy I could incorporate that as part of this pull request).

**Comment by onibrow** [comment]
I'll look into what sort of screw terminal we actually have today. I'll let you handle the description for the library parts.

**Comment by tobinsarah** [comment]
Sounds good. Sorry this for all the delays on my end.

Pin size is *probably* standard across different manufacturers, but it's good to check. I'm guessing the size mis-match is due to different fit styles, but you should make the drill size bigger because too small is much more of a problem than too big.

**Comment by tobinsarah** [comment]
merging so mohammed can use them, I'll add the drill size to the issue tracker.

**Pull request merged**
