### PR TITLE
Team Flag Rev. B

### PR DESCRIPTION
**Pull request by cduck**
Update labels for Rev B.  Add four extra status LEDs.  Align board to origin.  Move some silkscreen.

I am considering changing the headers to SMD headers for Rev. B also.

### CODE REVIEW

**Comment by tobinsarah** [comment]
Schematic:
* Delete "Team Flag" label, it's redundant/confusing. Make other labels large (size/style of "Team Flag" label that I want you to delete) so they stick out more.

Board:
* Delete extraneous ground wires in top left and right corners of board

**Comment by krystynneisess** [comment]
Ah!  One other thing:  the board's "last updated" date in the top copper layer is inconsistent with the schematic's date.

**Comment by cduck** [comment]
This depends on the SMD header pin pull request and is waiting until it is fixed and merged.

**Comment by cduck** [comment]
I think that's everything.

**Comment by dwai213** [comment]
- Highly recommend that the four added status LED have unique names instead of just all RED. Otherwise, it's not helpful for students

- Capitalize Smart Device
- Fix schematic spacing for the cap so that you can see connections are made
- Do the same for LED5

**Comment by cduck** [comment]
The LEDs are labeled LED1, 2, etc.  RED is the value.

**Comment by cduck** [comment]
All fixed.

**Comment by dwai213** [comment]
- Highly recommend that the four added status LED have unique names instead of just all RED. Otherwise, it's not helpful for students
- Ah, I see it now. I didn't see LED1-4 on the silk, all good for me

**Comment by cduck** [comment]
Merged.

**Pull request closed without merging**
