### PR TITLE
Version 4 smartsensor

### PR DESCRIPTION
**Pull request by jarzofjam**
Ahhhhhh

### CODE REVIEW

**Comment by tobinsarah** [comment]
Congratulations on your first pull request Janny! 

Here are a few things to fix. This may look like a lot, but don't panic! Most of these are easy to do and/or low importance. I've marked big problems with (IMPORTANT) -- everything else is cosmetic/good style. If you have questions about any of these suggestions (what I meant, how to do any of this, etc.), please ask me or Casey! I'm always interruptible at work session.

#SCHEMATIC:
1. Move everything so that the bottom left corner of the frame is at the origin (see http://staff.pierobotics.org/wiki/Electrical_style_guidelines#Conventions for details)
2. Fill out the info box in the bottom right corner (Casey or I can show you how to do this)
3. Please label net N$2 (I suggest "VBUS")
4. Label the different subcircuits on the schematic (you've already grouped them pretty nicely, just give a clear name so people can see at a glance what each group is for).
5. Please rotate the labels of C1, C2, and C4 to horizontal orientation.
6. I would tunnel to the solder jumpers rather than drawing a visible wire (but that's pretty minor).
7. (IMPORTANT) USB GND and SHIELD should be connected to board ground


#BOARD:
1. Change all fonts to vector
2. (IMPORTANT) Still need mounting holes (add the "STANDOFF" part). Ideally we would like one in each corner (see http://staff.pierobotics.org/wiki/Electrical_style_guidelines#Rules_2 for more details on standoff placement).
3. Add copyright text to bPlace layer
4. (MID-IMPT) Clean up (rotate and move around) part names and values so they all legible and do not overlap. This will require liberal use of the "smash" tool.
5. Fix square trace corners (should be 45º). Coordinates for the one I see is (1.056, 0.300); 
6. Fix acute and right angle traces (see instructions at http://staff.pierobotics.org/wiki/Electrical_style_guidelines#Special_Cases) (or bug Casey or me).


I know you're still working on routing, so here's some things to keep in mind while you do that: Keep traces as short and straight as possible. I noticed some places where your traces have unnecessary kinks--for example, at (1.062, 0.666).


That's all for now. Keep up the great work, and let me know if I can help!

**Comment by jarzofjam** [comment]
AHHHHHHHHHHHHHHH silkscreen is death, do not send off.

**Comment by cduck** [comment]
Merged.

**Comment by cduck** [comment]
Things still to fix:

- There are several places where silkscreen is still overlapping pads.
- The two polygons on the traces still have clearance errors.

**Pull request closed without merging**
