### PR TITLE
Add SMD package for 1X6 header to pie library.

### PR DESCRIPTION
**Pull request by tobinsarah**

### CODE REVIEW

**Comment by cduck** [comment]
Problem: The pad names in the package are not in order and connected to the wrong part pins.

- tKeepout needs include the pads that extend out to the top and bottom.
- Why is there a bKeepout region?  The component doesn't go through the board.
- Maybe say something more helpful in the package description.
- Show the physical position of the pins on the board in the tDocu layer.  Style guidelines: "Use tDocu to indicate physical size of part."

**Comment by cduck** [comment]
Also, DRC give stop errors for silkscreen that goes over the pads.  This silk screen should probably be removed.

**Comment by tobinsarah** [comment]
with the current tKeepout setup, you don't need to move the mosfets: 

screen shot 2015-11-01 at 12 41 40 pm

**Comment by cduck** [comment]
Looks good.  Merged.

**Pull request closed without merging**
