### PR TITLE
Fix silkscreen on Beaglebone top board

### PR DESCRIPTION
**Pull request by johnlimjsj**
- Change name from "Top Board" to "Woodstock"
- Switched the 12V and GND label to make it correct
- Change size of drill hole from 1.25 to 0.75
- Change 2.2uF capacitor to 2.2uF a polarised Tantalum Capacitor

### CODE REVIEW

**Comment by tobinsarah** [comment]
BOARD:
* I'm not sure that this is a problem, but the 2x20 pin headers aren't behaving like parts on the board... I can't select, move, or get info on them.
* Are c1 and c2 both polar? If so, I would put them in the same orientation, even if that means they don't line up. This might prevent soldering mistakes later.

SCHEMATIC (low priority):
* Tidy up: Component labels should be horizontal and should not overlap each other; ground and power symbols should be vertical.
* You can add your name to "design by" since you worked on it :)

**Comment by tobinsarah** [comment]
BOARD:
* I'm not sure that this is a problem, but the 2x20 pin headers aren't behaving like parts on the board... I can't select, move, or get info on them.
* Are c1 and c2 both polar? If so, I would put them in the same orientation, even if that means they don't line up. This might prevent soldering mistakes later.

SCHEMATIC (low priority):
* Tidy up: Component labels should be horizontal and should not overlap each other; ground and power symbols should be vertical.
* You can add your name to "design by" since you worked on it :)

**Comment by tobinsarah** [comment]
BOARD:
* I'm not sure that this is a problem, but the 2x20 pin headers aren't behaving like parts on the board... I can't select, move, or get info on them.
* Are c1 and c2 both polar? If so, I would put them in the same orientation, even if that means they don't line up. This might prevent soldering mistakes later.

SCHEMATIC (low priority):
* Tidy up: Component labels should be horizontal and should not overlap each other; ground and power symbols should be vertical.
* You can add your name to "design by" since you worked on it :)

**Comment by cduck** [comment]
One final thing: Both capacitors have the wrong polarity in the schematic.  You need to change it so the side with the + is connected to the higher voltage.  The parts will also have to be moved on the board.

**Comment by dwai213** [comment]
Hi John
This looks pretty good.
Just some more minor things
- LT323A label, can you change its size so that it's the same as all the other labels on the silk?
- Also, can you move it out of the way of the giant red ground pad for the 5V regulator?
- pioneers.berkeley.edu instead of pioners.berkeley.edu please :D
- Update the revision information? Isn't this revB? @cduck can correct me if I am wrong

Not so important, but why is [this](https://www.dropbox.com/s/5mne78lw5wkn745/Screenshot%202015-11-05%2001.18.05.png?dl=0) have a colliding silk? Is it possible to clean this up?

**Comment by cduck** [comment]
Yes, it should be RevB.

That silkscreen is on the top and bottom.  It's not colliding.

**Comment by cduck** [comment]
Merged.

**Pull request closed without merging**
