### PR TITLE
USB Micro AB SMD package and device AND GRIZZLY USB FIX

### PR DESCRIPTION
**Pull request by tobinsarah**
not sure why it can't merge automatically... sorry :/

### CODE REVIEW

**Comment by tobinsarah** [comment]
wait a bunch of these commits *SHOULD BE* redundant... I'm confused...

**Comment by tobinsarah** [comment]
okay sorry there are now two things in the same pull request Casey plz advise

**Comment by cduck** [comment]
I fixed the merge issues and put it here: https://github.com/cduck/tenshi/tree/usbPull

Can you check that all your changes are here before I merge it?

Thanks.

**Comment by tobinsarah** [comment]
The commit messages are all there, and the changes to the files are all
things that I expect to see. The files I pulled from this branch look good
in EAGLE. Is there anything else I should check?

**Comment by cduck** [comment]
Merged.

**Pull request closed without merging**
