### PR TITLE
Add 5V Rail to PDB

### PR DESCRIPTION
**Pull request by Sharabesh**
Schematic to come.

### CODE REVIEW

**Comment by tobinsarah** [comment]
Nice work! Please rename a few nets and parts for clarity:

* Rename the connectors so that they match the fuse names (e.g., currently CONN10 is wired to FUSE8. Change its name to CONN8.) 
** Note on renaming: You can't just rename the current CONN10 to CONN8 because there is already a CONN8 on the board. I usually get around this by first renaming things with their desired name doubled (so I would change CONN10 to CONN88 etc.) then renaming everything a second time to the actual desired name. This is kind of annoying, but you only need to change the four new connectors. The fuses are fine.

* Give descriptive names to all of the N$ nets (I see N$1 through N$5). N$1 should be '12V'. N$2 through N$5 should follow the conventions we used on the 12V side (for the wires between the connectors and the fuses).

For both of these you should use the NAME tool, which is three below the DELETE tool on the leftside toolbar (at least in my version of eagle):
screen shot 2016-08-27 at 10 55 16 pm

**Comment by Sharabesh** [comment]
Got it, I changed the names according to naming conventions and pushed back.

**Comment by tobinsarah** [comment]
Also! Just figured out how to add the proper info to the frame (the box in the bottom right corner of the schematic). Go to attributes, click on the frame's origin (lower left corner of frame), and change values accordingly.

I would say you should add it for practice, but for efficiency I can do it on my end.

**Comment by tobinsarah** [comment]
The net connecting fuses 7 through 10 needs to be named 12V, not 5V

**Pull request merged**
