### PR TITLE
Battery Buzzer Changes

### PR DESCRIPTION
**Pull request by abhishyantkhare**
Haven't finished board layout/routing

### CODE REVIEW

**Comment by tobinsarah** [comment]
Your commit should only change two files -- battery_buzzer.brd and battery_buzzer.sch

Please remove all other files from your commit.

**Comment by SamboyKirk** [comment]
We know about the drc stop mask issues, they are the result of letters being cut off by the holes.

**Comment by tobinsarah** [comment]
This list of things to do is pretty long, but not all of it needs to be done for revision A. If you have questions about any of these suggestions (what I meant, how to do any of this, etc.), please ask me or Casey! I'll be in 101 before noon, Casey will be there after 5pm.

#SCHEMATIC:
1. Label the different subcircuits on the schematic (just give a clear name so people can see at a glance what each group is for -- use the text tool).
2. Delete unused wires (such as the "tx" and "rx" in the bottom right).
3. Please label nets N$1 through N$7 with descriptive names
5. Please rotate the labels R10 to be horizontal.

#BOARD:
1. Change all fonts to vector
2. (IMPORTANT) Delete extra standoff (U$8) and silkscreen text (10k).
3. Move copper text onto board and update (ask Casey to clarify).
4. Remove redundant ground traces (I two: one from Q2 to R10, and one btw R5, R7, R8)
5. Fix names for the new headers: smash and set text "ratio" property to 15%

That's all for now. Keep up the great work, and let me know if I can help!

**Comment by dwai213** [comment]
+1 @tobinsarah for reviewing!

**Pull request closed without merging**
