### PR TITLE
Revision B of Arduino smart device shield

### PR DESCRIPTION
**Pull request by cduck**
- Add a connector for an external AVR programmer

### CODE REVIEW

**Comment by dwai213** [comment]
Suggestions:
 - SDA and SCL lines that go to D2, perhaps move them farther away ISP connectors so that the filled GND plane won't be as disjointed. Like [so](https://www.dropbox.com/s/56hvlyl4pke7vgx/Screenshot%202015-11-28%2010.15.37.png?dl=0)

**Comment by cduck** [comment]
- I did this to connect the ground plane and make it look better after ratsnest.  Would a single trace be better?  This is how the power plane looks with a single trace:
screen shot 2015-11-28 at 12 31 18 pm

- Fixed ground plane connectivity
- Yes.  I moved the ISP programmer connector.

**Comment by dwai213** [comment]
Yeah Casey, definitely not good with only one trace. The goal here is to reduce the width of a given segment of the plane to guard against manufacturing errors.

- One additional way to mitigate this is to move the IO9 trace further out, by using a smaller grid spacing (.025in?). Like [so](https://www.dropbox.com/s/u058gycpzfwsipw/Screenshot%202015-11-28%2015.33.43.png?dl=0)

- As for spaghetti trace, just draw all over the area between the 5V in the ISP and the strain relief (?) hole?
- Also, do you need to change out the strain relief hole size here as well?

**Comment by cduck** [comment]
How about this:
screen shot 2015-11-28 at 5 22 41 pm

- These strain relief holes are fine.

**Comment by dwai213** [comment]
Excellent.

**Comment by cduck** [comment]
Merged.

**Pull request closed without merging**
