### PR TITLE
Rename "Unpowered Smartsensor" to "Smartsensor" and move vias

### PR DESCRIPTION
**Pull request by cduck**
I nearly forgot.

Because this board is connected to every other board, unpowered smartsensor only applies when it is being used standalone.

### CODE REVIEW

**Comment by tobinsarah** [comment]
screen shot 2015-11-30 at 7 33 16 pm

Is the red vertical trace supposed to be connected to the via?

**Comment by cduck** [comment]
Run ratsnest.

On Nov 30, 2015, at 7:34 PM, Tobin Holcomb <notifications@github.com> wrote:

[image: screen shot 2015-11-30 at 7 33 16 pm]
<https://cloud.githubusercontent.com/assets/3431933/11491709/3fb89366-9799-11e5-8328-2dd3e9253dde.png>

Is the red vertical trace supposed to be connected to the via?

—
Reply to this email directly or view it on GitHub
<https://github.com/pioneers/tenshi/pull/306#issuecomment-160841386>.

**Comment by cduck** [comment]
I agree that the trace should be connected but I didn't change now it because this is how it was when we ordered Rev C.

Merged.

**Comment by tobinsarah** [comment]
yeah it's not that big a deal. I'll add it to the list of "fix next year"
things.

**Pull request closed without merging**
