### PR TITLE
Sharabesh2

### PR DESCRIPTION
**Pull request by Sharabesh**

### CODE REVIEW

**Comment by AravindK95** [comment]
@tobinsarah Do you want to merge this into tenshi/master instead of an experimental branch? If that is the case, then these commits should be a bit more refined before I can approve them.

- Please remove all eagle temp files from these commits (.s#N and .b#N files). Only the .brd and .sch file are needed.
- Please fix the typo in the commit message for f67d973923df92eabf99fc20707627f2e25af384
- Please move the new files into the eda/ folder
- The schematic has several overlaps between labels and parts. Please space out the components to avoid this.
- The label for CONN5 on the board layout is outside the board dimensions.

This all might be too much of a hassle, so merging into a new branch on tenshi might be an easier option for now.

**Comment by Sharabesh** [comment]
I made the changes you recommended to merge into the main Tenshi repository.

**Comment by tobinsarah** [comment]
- when I pull your files from github and open them on EAGLE, I get that the schematic and board are inconsistent. @AravindK95, do you also see this right now? (If not, I may just be pulling wrong). @Sharabesh -- please open the board and schematic files in EAGLE and fix any inconsistencies.
- Please rename your "SR_board" to be descriptive of the type of board you designed (it's a "power distribution board", which is a bit long, so feel free to abbreviate to "pdb_SR" or "power_board_SR" or similar, whatever you feel is clearest). Please have the board name come before your identifier, though, so it will be easier to spot in lists of files.

**Comment by tobinsarah** [comment]
Schematic:
-- move frame and all components into the left quadrant (frame's bottom left corner should be at the origin (x=0.0, y=0.0), which is marked by this symobl: 
screen shot 2016-07-09 at 2 03 35 am

-- replace GND symbol with the "GND" symbol from the pie library

**Pull request merged**
